language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
script: make run_all_in_parallel
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: nh9yoo6VE0EZr9GyduEp/urC3G1Fq0/h5349c5kIWKCeBTYjISz1cT5UKQPXnWYp/qZzgzN5Ro6nVnbeH0buGKa5eYVF54mny/cXkLdAUPBRWEMogyBElrmYtoO+tzxFsbkWSBaGyfaLQQeRgNf62mpWm3HRpoPlmCNFICXIAc7cT10tUTH+vJ/1Mio2RYBFLRK4UCHe6NKiy2GZSsY6vU5O92KXgUI8CHxoS+0EwxVPoPAGSsVd1hlUG4V93o2e4v/ThLHzxa0VqaheeH1R+FhYU9IAuu4A2IWOxwR6QoL7i8EASYpgFSAAJXpk3++JrXft2iMfHYc33phC8o87axym7Ewm7dhfm20iT73occGjMqAstIPZ8YC+tOmyiEnxHd9uFdtlHaygdSTy16B+akpdDIfpnPsrgOdJdC2aMnQkL9yoqEl/EGJ4VAXfonpIXa3xu20t5g2QbvldJbZqt0yT6nJeTxmFQrC4VRlHDsbeQDu00Hxcnb9zJUB3UbV5N1Sn/ISj0FXJV1oh+iXVW3eFHi4Rwhbi9xUY2yrm89Qk+KCMPNBCl13XSwrAvW4FpTDei4CRGe5GTLOIFyyKsXJqiUGQRmQtX4IIga4OwTTLNMhJtFV+4QhA0ICl4IlkJgfKVYarspkYJrL5pKVmSdgUv/WRQACctfIJmsSB1Wk=
