language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
script: make run_all_in_parallel
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: OkkRYKFRxGNk9L8QwDnYbTazII2ScdxZvG1uo+6RFiI8Ek7vPsjLdHK61ACCJWi57C6nHJFnPdwUHZqz7bLyMLJDhVBTBpGGBBHdQh1l3SMah3muNPpqcs5V8JVXk1gUgbgdSYSmB2h6fh7d0V7YCY75ubEiOxpTzQE1Pk1Jzr9jnJEtGTLXhnQDugVkjXOIcoqgtuIlKI3LhnvMAx8yMTZr7mxAluxw3bbLaB5lYZ7aczPq118zuKM4rXPOyiTCY4KCFWNsH57FxH/uGrXbfOAGZOH5Vj6hUQCbtULkvmWz26X5Z48T1ENHMTWY5lbCuScvsEfeCT66MUconDpy59gD3KkNVdsDO5SfwILOiHIA9f99hAf6Cp9QYaBRADcngaknT+aehvwDvBTqJGgIu6SHhdfgcOLXxcb0oEn7IUeWglhBCRyuoloWlT+gYQqTiVPJ82kS/oQo4YgHXA2iDagnO+iF1SQzIMgBB/GzuYtJCIVT3qJbUJGbEW0oHTuZfz8js8LSP6sGXhjqO8v+NSk35ZO3xz0nflD86py+Y6jrhuUDRrVixuYPalkO2VpvMAmi+IlvnUdvDe6aR9MHOfe4vnJ4JT4Yxp6b2NfqYeOV+vxS4u+gFFQ2DKV+RtkvnC4H33AdQWhfteoriG56lN4qs+YbVk/ZOtJ8gXGBNvM=
